# Generated by Django 5.0.1 on 2024-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_pagemodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagemodel',
            name='img',
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='books.imagemodel'),
        ),
    ]
